#!/usr/bin/env python3
"""Render each fixture at 26.2.4.2 and print what its PDF actually paints.

The generator for `fixture-reference/painted.txt`, which had none: every expectation in
`results.md` §1 and §2 is read back out of this, so it has to be re-derivable rather than
transcribed. Filled rectangles, stroked paths, embedded images and text spans with their
colours — and a gradient, which VCL writes as hundreds of one-colour slices whose count is
the output device's own pixel width, summarised per row rather than listed.

Rendering is one fixture at a time into its **own** output directory, because
`soffice --convert-to` names its output after the input's stem alone: two fixtures sharing a
stem would silently overwrite one another's PDF and each would be scored against the other's
rendering.

Usage: fixture-paint.py <fixture-dir> <workdir> [stem ...]
"""
import pathlib
import subprocess
import sys

import pymupdf

SOFFICE = "/opt/libreoffice26.2/program/soffice"


def convert(src, outdir, fmt, profile):
    outdir.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [SOFFICE, "--headless", f"-env:UserInstallation=file://{profile}",
         "--convert-to", fmt, "--outdir", str(outdir), str(src)],
        capture_output=True, timeout=600, check=False)
    found = sorted(outdir.glob(f"*.{fmt}"))
    if len(found) != 1:
        raise SystemExit(f"{src.name}: expected one .{fmt}, got {[f.name for f in found]}")
    return found[0]


def hexof(c):
    return "#%02x%02x%02x" % tuple(int(round(v * 255)) for v in c)


def rows(pdf):
    """Every mark the page carries, gradients folded into one row each."""
    out = []
    for pno, page in enumerate(pymupdf.open(pdf), 1):
        runs = []           # consecutive same-y fills, which is how a gradient arrives
        for d in page.get_drawings():
            r = d["rect"]
            if d["type"] in ("f", "fs") and d.get("fill") is not None:
                runs.append((pno, hexof(d["fill"]), r))
            elif d["type"] == "s" and d.get("color") is not None:
                out.append(f"    p{pno} stroke {hexof(d['color'])} "
                           f"x {r.x0:8.2f}-{r.x1:8.2f} y {r.y0:8.2f}-{r.y1:8.2f}")
        i = 0
        while i < len(runs):
            j = i
            while j + 1 < len(runs) and abs(runs[j + 1][2].y0 - runs[i][2].y0) < 0.01:
                j += 1
            n = j - i + 1
            if n > 20:      # a gradient: many one-colour slices at one y
                x0 = min(r.x0 for _, _, r in runs[i:j + 1])
                x1 = max(r.x1 for _, _, r in runs[i:j + 1])
                out.append(f"    p{pno} gradient {n} slices x {x0:.2f}-{x1:.2f} "
                           f"y {runs[i][2].y0:.2f}  {runs[i][1]} .. {runs[j][1]}")
            else:
                for p, c, r in runs[i:j + 1]:
                    out.append(f"    p{p} fill   {c} "
                               f"x {r.x0:8.2f}-{r.x1:8.2f} y {r.y0:8.2f}-{r.y1:8.2f}")
            i = j + 1
        for img in page.get_images(full=True):
            for rect in page.get_image_rects(img[0]):
                out.append(f"    p{pno} image  {img[2]}x{img[3]} "
                           f"at ({rect.x0:.2f}, {rect.y0:.2f})")
        for block in page.get_text("dict")["blocks"]:
            for line in block.get("lines", []):
                for span in line["spans"]:
                    col = "#%06x" % span["color"]
                    out.append(f"    p{pno} span   {col} "
                               f"x {span['bbox'][0]:8.2f} y {span['bbox'][1]:8.2f} "
                               f"{span['text']!r}")
    return out


def main():
    src, work = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
    stems = sys.argv[3:]
    files = sorted(src.glob("sheet-cf-*.xlsx"))
    if stems:
        files = [f for f in files if f.stem in stems]

    print("# `soffice --convert-to pdf` of each fixture, LibreOffice 26.2.4.2, "
          "regenerated by fixture-paint.py.")
    print("# Filled rectangles, stroked paths, embedded images and text spans with their colours.")
    print("# A gradient arrives as hundreds of one-colour slices; those are summarised per row.")
    for n, f in enumerate(files):
        out = work / f.stem                       # one directory per fixture, never shared
        pdf = convert(f, out, "pdf", work / f"profile-{n}")
        print(f"\n=== {pdf.name}")
        for line in rows(pdf):
            print(line)


if __name__ == "__main__":
    main()
